name: Pull Request
on:
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"
jobs:
  pull_request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Check code format
        run: yarn check-code-format
      - name: ESLint validate
        run: yarn eslint:validate
